### ISSUE TITLE
Webpack 5 Support & 1.0 meta issue

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#880]
Hi!

This issue tracks things that we want to get done before releasing a 1.0 of Encore with Webpack 5 support:

* [X] A) Initial Webpack 5 support #645 
* [X] B) Using old watchOptions regexp & removing Node 13 support #878
* [X] C) Collect changes (mostly from #645) and add them to CHANGELOG #883
* [X] D) Integrate [Asset Modules](https://webpack.js.org/guides/asset-modules/) for images, fonts, etc #883 
* [~] ~~E) potentially use WebpackManifestPlugin also for entrypoints.json~~ Will consider later
* [x] F) Check into our `stats` config - should we "hijack" this less and allow for more normal output?
* [X] G) add method to enable new persistent caching - #884
* [x] H) Decide on a backwards-compatibility (BC) promise related to Webpack dependencies (e.g. if we bump `@babel/core` from v7 to v8, does that require a new major version of Encore? OR what if we drop support for `sass-loader` v9 (which is a library version that the user controls) - does that require a new major version of Encore?
* [X] I) Ideally, make all the tests that rely in hashes more forgiving - don't skip them entirely, but match for "fuzzines" - e.g. that we expect a file matching a pattern (faux example: `main.[alpha length 8].js`). - #883 
* [~] ~~J) Make a decision about `friendly-errors-webpack-plugin` which appears abandoned https://github.com/geowarin/friendly-errors-webpack-plugin/issues/123~~ we will keep for now, it works fine, but the warning when installing Encore is annoying :/ 
* [x] L) Merge new Stimulus-bridge support #888
* [x] K) #889 - bumped `@babel/preset-env`

**Comment by versedi** [comment]
>  H) Decide on a backwards-compatibility (BC) promise related to Webpack dependencies (e.g. if we bump @babel/core from v7 to v8, does that require a new major version of Encore? OR what if we drop support for sass-loader v9 (which is a library version that the user controls) - does that require a new major version of Encore?

IMHO it shouldn't rely on the major/minor update of the dependency's version, but instead on the fact if the dependency update breaks anything inside encore - eg. configuration syntax changes or behaviour of something changes.

**Comment by weaverryan** [comment]
About dependencies:

A) If we bump a major version of our direct `dependencies`, then would require a new major version of Encore if it can (in any reasonable way) affect our users. For example, a new version of `semver` would not affect our users (this is used internally for our own purposes) but a new version of `babel` *could* reasonably affect users.

B) If we bump a major version of a `devDependency` like `sass-loader`, then this is actually just a recommendation on what the user needs to have installed. Upgrading Encore does not actually upgrade their dependency. So, no new major version of Encore is needed. Of course, if we needed to change our integration with sass-loader (so that the old `sass-loader` will suddenly not work with the new version of Encore), then that would require a major break. In general, we would try to not "remove" support for old `devDependency` versions during minor Encore versions.
